import java.util.Scanner ;
import java.util.Random; ;

class Game{
	public int number ;
	public int inputNumber ;
	public int noOfGuesses ;
	
	Scanner sc = new Scanner(System.in);
	
	Game(){
        Random rand = new Random();
        this.number = rand.nextInt(100);
    }
    int takeUserInput(){
        System.out.print("Guess the number :- ");
        inputNumber = sc.nextInt();
        return inputNumber ;
    }
    void rules() {
    	System.out.println("                 WELCOME TO NUMBER GUESSING GAME  ");
    	System.out.println("     If You Guess wrong Number , Then it show you , Your guessing Number is too High or Low");
    }
    boolean isCorrectNumber(){
        noOfGuesses++;
        if (inputNumber==number){
            System.out.format("Yes you guessed it right, it was :- %d\nYou guessed it in %d attempts", number, noOfGuesses);
            return true;
        }
        else if(inputNumber<number){
            System.out.println("Your Guess Number is Too low...");
        }
        else if(inputNumber>number){
            System.out.println("your Guess Number is Too high...");
        }
        return false;
    }
}

public class GuessTheNumber {
    public static void main(String[] args) {
		/*
		 NUMBER GUESSING GAME

The fun and easy project "Guess the Number" is a short java project that allows the user 
to guess the number generated by the computer & involves the following steps

1. The system generates a random number from a given range, say 1 to 100

2. The user is prompted to enter their given number in a displayed dialogue box. 

3. The computer then tells if the entered number matches the guesses number or it is

higher/lower than the generated number

4 The game continues under the user guessing the number

You can also incorporate further details as

	-->Limiting the number of attempts

	-->Adding more rounds

	-->Displaying score

	-->Giving points based on the number of attempts.
		 */
		
		Game g = new Game() ;
		g.rules() ;
		boolean b = false ;
		while( !b ) {
			g.takeUserInput();
			b = g.isCorrectNumber() ;
		}
	}
}
